`include "slow_vdd1v0_basicCells.v"
// Generated by Cadence Genus(TM) Synthesis Solution 19.15-s090_1
// Generated on: Mar  8 2021 17:21:02 EST (Mar  8 2021 22:21:02 UTC)

// Verification Directory fv/clb_top 

module sram_ADDR_WIDTH4(clk, raddr, rdata, waddr, wdata, we, scan_in,
     scan_out, scan_en);
  input clk, wdata, we, scan_in, scan_en;
  input [3:0] raddr, waddr;
  output rdata, scan_out;
  wire clk, wdata, we, scan_in, scan_en;
  wire [3:0] raddr, waddr;
  wire rdata, scan_out;
  wire [15:0] sram_data;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10;
  MXI4X1 g724__2398(.A (n_7), .B (n_10), .C (n_8), .D (n_9), .S0
       (raddr[3]), .S1 (raddr[2]), .Y (rdata));
  AOI222X1 g725__5107(.A0 (sram_data[10]), .A1 (n_1), .B0 (n_0), .B1
       (n_4), .C0 (sram_data[11]), .C1 (n_2), .Y (n_10));
  AOI222X1 g726__6260(.A0 (sram_data[14]), .A1 (n_1), .B0 (n_0), .B1
       (n_6), .C0 (scan_out), .C1 (n_2), .Y (n_9));
  AOI222X1 g727__4319(.A0 (sram_data[6]), .A1 (n_1), .B0 (n_0), .B1
       (n_3), .C0 (sram_data[7]), .C1 (n_2), .Y (n_8));
  AOI222X1 g728__8428(.A0 (sram_data[2]), .A1 (n_1), .B0 (n_0), .B1
       (n_5), .C0 (sram_data[3]), .C1 (n_2), .Y (n_7));
  MX2X1 g729__5526(.A (sram_data[12]), .B (sram_data[13]), .S0
       (raddr[0]), .Y (n_6));
  MX2X1 g730__6783(.A (sram_data[0]), .B (sram_data[1]), .S0
       (raddr[0]), .Y (n_5));
  MX2X1 g731__3680(.A (sram_data[8]), .B (sram_data[9]), .S0
       (raddr[0]), .Y (n_4));
  MX2X1 g732__1617(.A (sram_data[4]), .B (sram_data[5]), .S0
       (raddr[0]), .Y (n_3));
  AND2X1 g733__2802(.A (raddr[1]), .B (raddr[0]), .Y (n_2));
  NOR2X1 g734__1705(.A (raddr[0]), .B (n_0), .Y (n_1));
  INVX2 g735(.A (raddr[1]), .Y (n_0));
  SDFFQX1 \sram_data_reg[11] (.CK (clk), .D (sram_data[11]), .SI
       (sram_data[10]), .SE (scan_en), .Q (sram_data[11]));
  SDFFQX1 \sram_data_reg[2] (.CK (clk), .D (sram_data[2]), .SI
       (sram_data[1]), .SE (scan_en), .Q (sram_data[2]));
  SDFFQX1 \sram_data_reg[3] (.CK (clk), .D (sram_data[3]), .SI
       (sram_data[2]), .SE (scan_en), .Q (sram_data[3]));
  SDFFQX1 \sram_data_reg[10] (.CK (clk), .D (sram_data[10]), .SI
       (sram_data[9]), .SE (scan_en), .Q (sram_data[10]));
  SDFFQX1 \sram_data_reg[0] (.CK (clk), .D (sram_data[0]), .SI
       (scan_in), .SE (scan_en), .Q (sram_data[0]));
  SDFFQX1 \sram_data_reg[12] (.CK (clk), .D (sram_data[12]), .SI
       (sram_data[11]), .SE (scan_en), .Q (sram_data[12]));
  SDFFQX1 \sram_data_reg[13] (.CK (clk), .D (sram_data[13]), .SI
       (sram_data[12]), .SE (scan_en), .Q (sram_data[13]));
  SDFFQX1 \sram_data_reg[4] (.CK (clk), .D (sram_data[4]), .SI
       (sram_data[3]), .SE (scan_en), .Q (sram_data[4]));
  MDFFHQX4 \sram_data_reg[15] (.CK (clk), .D0 (scan_out), .D1
       (sram_data[14]), .S0 (scan_en), .Q (scan_out));
  SDFFQX1 \sram_data_reg[6] (.CK (clk), .D (sram_data[6]), .SI
       (sram_data[5]), .SE (scan_en), .Q (sram_data[6]));
  SDFFQX1 \sram_data_reg[5] (.CK (clk), .D (sram_data[5]), .SI
       (sram_data[4]), .SE (scan_en), .Q (sram_data[5]));
  SDFFQX1 \sram_data_reg[1] (.CK (clk), .D (sram_data[1]), .SI
       (sram_data[0]), .SE (scan_en), .Q (sram_data[1]));
  SDFFQX1 \sram_data_reg[14] (.CK (clk), .D (sram_data[14]), .SI
       (sram_data[13]), .SE (scan_en), .Q (sram_data[14]));
  SDFFQX1 \sram_data_reg[7] (.CK (clk), .D (sram_data[7]), .SI
       (sram_data[6]), .SE (scan_en), .Q (sram_data[7]));
  SDFFQX1 \sram_data_reg[8] (.CK (clk), .D (sram_data[8]), .SI
       (sram_data[7]), .SE (scan_en), .Q (sram_data[8]));
  SDFFQX1 \sram_data_reg[9] (.CK (clk), .D (sram_data[9]), .SI
       (sram_data[8]), .SE (scan_en), .Q (sram_data[9]));
endmodule

module clb_top(clk, clb_in, out, scan_in, scan_out, scan_en);
  input clk, scan_in, scan_en;
  input [3:0] clb_in;
  output out, scan_out;
  wire clk, scan_in, scan_en;
  wire [3:0] clb_in;
  wire out, scan_out;
  wire [3:0] inst_clb_test_module_ble_in_conn;
  wire [11:0] inst_clb_test_module_inst_clb_ble_conn_mux_config;
  wire UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z1,
       UNCONNECTED_HIER_Z2, UNCONNECTED_HIER_Z3, UNCONNECTED_HIER_Z4,
       inst_clb_test_module_inst_ble_lut_ff,
       inst_clb_test_module_inst_ble_lut_table_out;
  wire inst_clb_test_module_inst_clb_ble_conn_n_18,
       inst_clb_test_module_inst_clb_ble_conn_n_19,
       inst_clb_test_module_inst_clb_ble_conn_n_20,
       inst_clb_test_module_inst_clb_ble_conn_n_21,
       inst_clb_test_module_is_comb, inst_clb_test_module_scan_conn_1,
       n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18;
  sram_ADDR_WIDTH4 inst_clb_test_module_inst_ble_inst_lut_data(.clk
       (clk), .raddr (inst_clb_test_module_ble_in_conn), .rdata
       (inst_clb_test_module_inst_ble_lut_table_out), .waddr
       ({UNCONNECTED_HIER_Z2, UNCONNECTED_HIER_Z1, UNCONNECTED_HIER_Z0,
       UNCONNECTED_HIER_Z}), .wdata (UNCONNECTED_HIER_Z3), .we
       (UNCONNECTED_HIER_Z4), .scan_in
       (inst_clb_test_module_scan_conn_1), .scan_out (scan_out),
       .scan_en (scan_en));
  CLKBUFX2 inst_clb_test_module_inst_clb_ble_conn_cdn_loop_breaker(.A
       (out), .Y (inst_clb_test_module_inst_clb_ble_conn_n_18));
  CLKBUFX2 inst_clb_test_module_inst_clb_ble_conn_cdn_loop_breaker4(.A
       (out), .Y (inst_clb_test_module_inst_clb_ble_conn_n_19));
  CLKBUFX2 inst_clb_test_module_inst_clb_ble_conn_cdn_loop_breaker5(.A
       (out), .Y (inst_clb_test_module_inst_clb_ble_conn_n_20));
  CLKBUFX2 inst_clb_test_module_inst_clb_ble_conn_cdn_loop_breaker6(.A
       (out), .Y (inst_clb_test_module_inst_clb_ble_conn_n_21));
  CLKMX2X4 g215__5122(.A (inst_clb_test_module_inst_ble_lut_ff), .B
       (inst_clb_test_module_inst_ble_lut_table_out), .S0
       (inst_clb_test_module_is_comb), .Y (out));
  DFFHQX1 inst_clb_test_module_inst_ble_lut_ff_reg(.CK (clk), .D
       (inst_clb_test_module_inst_ble_lut_table_out), .Q
       (inst_clb_test_module_inst_ble_lut_ff));
  OAI211X1 g571__8246(.A0
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[9]), .A1
       (n_11), .B0 (n_1), .C0 (n_16), .Y
       (inst_clb_test_module_ble_in_conn[3]));
  OAI211X1 g572__7098(.A0
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[6]), .A1
       (n_14), .B0 (n_0), .C0 (n_15), .Y
       (inst_clb_test_module_ble_in_conn[2]));
  OAI2BB1X1 g573__6131(.A0N
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[3]), .A1N
       (n_9), .B0 (n_18), .Y (inst_clb_test_module_ble_in_conn[1]));
  AO21X1 g574__1881(.A0
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[0]), .A1
       (n_7), .B0 (n_17), .Y (inst_clb_test_module_ble_in_conn[0]));
  AOI2BB2X1 g575__5115(.A0N
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[3]), .A1N
       (n_12), .B0
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[5]), .B1
       (inst_clb_test_module_inst_clb_ble_conn_n_20), .Y (n_18));
  OAI21X1 g576__7482(.A0
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[0]), .A1
       (n_13), .B0 (n_2), .Y (n_17));
  NAND2X1 g577__4733(.A
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[9]), .B
       (n_10), .Y (n_16));
  NAND2X1 g578__6161(.A
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[6]), .B
       (n_8), .Y (n_15));
  AOI22X1 g579__9315(.A0 (clb_in[0]), .A1 (n_5), .B0 (clb_in[2]), .B1
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[7]), .Y
       (n_14));
  AOI22X1 g580__9945(.A0 (clb_in[0]), .A1 (n_6), .B0 (clb_in[2]), .B1
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[1]), .Y
       (n_13));
  AOI22X1 g581__2883(.A0 (clb_in[0]), .A1 (n_3), .B0 (clb_in[2]), .B1
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[4]), .Y
       (n_12));
  AOI22X1 g582__2346(.A0 (clb_in[0]), .A1 (n_4), .B0 (clb_in[2]), .B1
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[10]), .Y
       (n_11));
  MX2X1 g583__1666(.A (clb_in[1]), .B (clb_in[3]), .S0
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[10]), .Y
       (n_10));
  MX2X1 g584__7410(.A (clb_in[1]), .B (clb_in[3]), .S0
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[4]), .Y
       (n_9));
  MX2X1 g585__6417(.A (clb_in[1]), .B (clb_in[3]), .S0
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[7]), .Y
       (n_8));
  MX2X1 g586__5477(.A (clb_in[1]), .B (clb_in[3]), .S0
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[1]), .Y
       (n_7));
  NOR2X1 g587__2398(.A
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[2]), .B
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[1]), .Y
       (n_6));
  NOR2X1 g588__5107(.A
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[8]), .B
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[7]), .Y
       (n_5));
  NOR2X1 g589__6260(.A (inst_clb_test_module_scan_conn_1), .B
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[10]), .Y
       (n_4));
  NOR2X1 g590__4319(.A
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[4]), .B
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[5]), .Y
       (n_3));
  NAND2X1 g591__8428(.A (inst_clb_test_module_inst_clb_ble_conn_n_21),
       .B (inst_clb_test_module_inst_clb_ble_conn_mux_config[2]), .Y
       (n_2));
  NAND2X1 g592__5526(.A (inst_clb_test_module_inst_clb_ble_conn_n_18),
       .B (inst_clb_test_module_scan_conn_1), .Y (n_1));
  NAND2X1 g593__6783(.A (inst_clb_test_module_inst_clb_ble_conn_n_19),
       .B (inst_clb_test_module_inst_clb_ble_conn_mux_config[8]), .Y
       (n_0));
  SDFFQX1
       \inst_clb_test_module_inst_clb_ble_conn_inst_config_sftreg_reg_data_reg[11]
       (.CK (clk), .D (inst_clb_test_module_scan_conn_1), .SI
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[10]), .SE
       (scan_en), .Q (inst_clb_test_module_scan_conn_1));
  SDFFQX1
       \inst_clb_test_module_inst_clb_ble_conn_inst_config_sftreg_reg_data_reg[3]
       (.CK (clk), .D
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[3]), .SI
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[2]), .SE
       (scan_en), .Q
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[3]));
  SDFFQX1
       \inst_clb_test_module_inst_clb_ble_conn_inst_config_sftreg_reg_data_reg[4]
       (.CK (clk), .D
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[4]), .SI
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[3]), .SE
       (scan_en), .Q
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[4]));
  SDFFQX1
       \inst_clb_test_module_inst_clb_ble_conn_inst_config_sftreg_reg_data_reg[0]
       (.CK (clk), .D
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[0]), .SI
       (inst_clb_test_module_is_comb), .SE (scan_en), .Q
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[0]));
  SDFFQX1 inst_clb_test_module_inst_is_comb_sftreg_reg_data_reg(.CK
       (clk), .D (inst_clb_test_module_is_comb), .SI (scan_in), .SE
       (scan_en), .Q (inst_clb_test_module_is_comb));
  SDFFQX1
       \inst_clb_test_module_inst_clb_ble_conn_inst_config_sftreg_reg_data_reg[5]
       (.CK (clk), .D
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[5]), .SI
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[4]), .SE
       (scan_en), .Q
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[5]));
  SDFFQX1
       \inst_clb_test_module_inst_clb_ble_conn_inst_config_sftreg_reg_data_reg[10]
       (.CK (clk), .D
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[10]), .SI
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[9]), .SE
       (scan_en), .Q
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[10]));
  SDFFQX1
       \inst_clb_test_module_inst_clb_ble_conn_inst_config_sftreg_reg_data_reg[1]
       (.CK (clk), .D
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[1]), .SI
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[0]), .SE
       (scan_en), .Q
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[1]));
  SDFFQX1
       \inst_clb_test_module_inst_clb_ble_conn_inst_config_sftreg_reg_data_reg[7]
       (.CK (clk), .D
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[7]), .SI
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[6]), .SE
       (scan_en), .Q
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[7]));
  SDFFQX1
       \inst_clb_test_module_inst_clb_ble_conn_inst_config_sftreg_reg_data_reg[8]
       (.CK (clk), .D
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[8]), .SI
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[7]), .SE
       (scan_en), .Q
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[8]));
  SDFFQX1
       \inst_clb_test_module_inst_clb_ble_conn_inst_config_sftreg_reg_data_reg[2]
       (.CK (clk), .D
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[2]), .SI
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[1]), .SE
       (scan_en), .Q
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[2]));
  SDFFQX1
       \inst_clb_test_module_inst_clb_ble_conn_inst_config_sftreg_reg_data_reg[9]
       (.CK (clk), .D
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[9]), .SI
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[8]), .SE
       (scan_en), .Q
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[9]));
  SDFFQX1
       \inst_clb_test_module_inst_clb_ble_conn_inst_config_sftreg_reg_data_reg[6]
       (.CK (clk), .D
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[6]), .SI
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[5]), .SE
       (scan_en), .Q
       (inst_clb_test_module_inst_clb_ble_conn_mux_config[6]));
endmodule

